[package]
org = "chathura"
name = "assign_or_extend_a_task"
version = "0.1.0"
distribution = "2201.11.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "hubspot.crm.engagements.tasks"
version = "1.0.0"
repository = "local"
